name: Pack patches

on: [push, pull_request]

jobs:
  pack:
    name: Pack and publish patches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archives
        run: |
          7z a -r patches.zip ./patches/*

      - name: Upload archives
        uses: actions/upload-artifact@v4
        with:
          name: patches
          path: ./patches.zip
          if-no-files-found: error

      - name: Update tag
        uses: actions/github-script@v7
        if: github.ref == 'refs/heads/main'
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest',
              sha: context.sha,
              force: true
            })

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          make_latest: true
          generate_release_notes: true
          tag_name: latest
          fail_on_unmatched_files: true
          name: Latest Build
          body: Test
          files: ./patches.zip
